[package]
name = "space-invaders"
version = "0.1.0"
edition = "2021"
author = ["Victor Gutierrez"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
